version: '3.8'

services:
  # --- BACKEND ---
  backend:
    build: ./backend
    container_name: retrogames-api
    ports:
      - "9090:9090"  # <--- CAMBIO IMPORTANTE: Puerto 9090
    environment:
      # Sobrescribimos la config de tu archivo properties:
      # 1. Usamos 'db' en vez de 'localhost'
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/retrogames_db?allowPublicKeyRetrieval=true&useSSL=false
      # 2. Tu usuario es root
      - SPRING_DATASOURCE_USERNAME=root
      # 3. Tu contraseña estaba vacía en el archivo, aquí definimos una para Docker
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    container_name: retrogames-web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # --- BASE DE DATOS ---
  db:
    image: mysql:8.0
    container_name: retrogames-db
    environment:
      - MYSQL_DATABASE=retrogames_db
      - MYSQL_ROOT_PASSWORD=root  # <--- Esta contraseña debe coincidir con la de arriba
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
