version: '3.8'

services:
  # --- 1. TU BACKEND (Spring Boot) ---
  backend:
    build: ./backend
    container_name: retrogames-api
    ports:
      - "8080:8080"
    environment:
      # Conecta con el servicio 'db' definido abajo
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/retrogames_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  # --- 2. TU FRONTEND (Angular + Nginx) ---
  frontend:
    build: ./frontend
    container_name: retrogames-web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # --- 3. BASE DE DATOS (MySQL) ---
  db:
    image: mysql:8.0
    container_name: retrogames-db
    environment:
      - MYSQL_DATABASE=retrogames_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge